apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana-lb2
  name: grafana-lb2
spec:
  ports:
  - name: 3000-3010
    port: 3000
    protocol: TCP
    targetPort: 3010
  selector:
    app.kubernetes.io/instancer: prometheus-stack
    app.kubernetes.io/name: grafana 
  type: LoadBalancer
status:
  loadBalancer: {}
