apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: NFS_SERVER
              value: 192.168.30.10
            - name: NFS_PATH
              value: /mnt/k3s_ext/k3s-nfs
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.30.10
            path: /mnt/k3s_ext/k3s-nfs
