apiVersion: v1
data:
    password: ENC[AES256_GCM,data:AG9iWeVFZx/jWfGDLQgBx3OQJp0C7AKzl9BFZg==,iv:JzPQlAWm/WTPkjaGEeniVJfj8neb9ZKkHeMqG5GopHk=,tag:k2ZbSL2hDKWKDQNd7YwaKg==,type:str]
    user: ENC[AES256_GCM,data:CBlqb/4s0WA=,iv:BxF7ImLKqUDS0olYn62Gg3r307hkTUGPQb5ovBleLy4=,tag:94HBcSZglGTMYNz4lbc0MQ==,type:str]
kind: Secret
metadata:
    name: grafana-admin-user
sops:
    age:
        - recipient: age10k28kkfyvws4ukkk4qy5aw5talf24cyh9xluhxdmeysflgza3gsqvazsek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMk1zOG1NT3F5LzN2dGQr
            L3dFMFAveUxqSGg5RkRCVlYvVndkS3JYVUVJCmszYW9VQ05zV25UeElwbG03TEtV
            WFZNS0lhcEd0aGt1WlJHOHhndWRzUW8KLS0tIFhDRVNTQW1nYzZqNk9LbnorcnVO
            dWpubUI0RVNzV2s4VUpJdEN6L1V0dTQK3y2YS8gaq1N6SNobzdMXoGkpmwRPSiJE
            tATEy5qkRoGRpM4Fleo23NPdtpA9viEIMf0eEEJpek9Ew6WMl6lh8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T22:37:57Z"
    mac: ENC[AES256_GCM,data:vkwpsXijOwzpHS3umn10wuPXkW33sbxuLPmgVUtrO8HrDlV8usYsmtJphmAjod8hTTMpy3kJ2mJDuHHiniDFsCOCrwF7qmZUdncOb/2FxT3iXx135yVXwD0GV25mLTR2Qyn1wEa2M5BLhbnJA94Gv+/EsPhpswUBGHiBs/ZoZWE=,iv:Gux1X4EBcfdbRyG2+H2+i5NkDOprOMxFIkOaOBlUs5g=,tag:QEaZIofAK4uJRhKVXN1DVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
