apiVersion: v1
data:
    password: ENC[AES256_GCM,data:oInvjtL3+DLB40E9Eb5zc6bVqyR4FeD71l/I9Q==,iv:HCiYRPayz7XtQ9i0PE2vbHZ5ppfUCFW/r0serTtqCfY=,tag:flyxrhdFKI+5ogPXZYV1wQ==,type:str]
kind: Secret
metadata:
    name: grafana-admin-password
sops:
    age:
        - recipient: age10k28kkfyvws4ukkk4qy5aw5talf24cyh9xluhxdmeysflgza3gsqvazsek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpc3JPU3BVa25DL016VGgr
            NmRneE5iWEpvQ1o4K2JtbmlYSVROVGl0SkV3Cit6aE1COHFDRW9xSjJzQmE4Vlpy
            czFZeUNXa1J6Wmh3aHZYMGVUaVhxamcKLS0tIFpidXVWSWR2V1NwUkZnNFkybmdr
            ZUhzdlh1TEtWbU0ya29jejlPaFNsb0EK4eoMMOw6ShuEwG76HBi1bo+CoyggHgn9
            RbP2slTvckiJ8kjH9PpLOGe/BwGC1mOvnOyiZELuIY3nU+Q9j1Lccg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T22:14:19Z"
    mac: ENC[AES256_GCM,data:dVhAEumat32wlOKgwotsF8LSN4rMIaV84WVNcwei0GaRxxvOiuvK1gVxvVGiRBWVQxGHdFD+fMPBUDVoB3vExZghuo8NCKCwrYV+3QRWUtPm2l6/7pg0QYblqQJ0FIi7Qk+ztbjWcAuu+hVFo49gH9njfcOHFAXYJBosFIFOfjg=,iv:w0jTPVKrtYHeqdrXQVHvt1yqV3Bauz3vY1uPamrc1ZM=,tag:pWJe2KzlIW6PGesngXDU0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
