apiVersion: v1
data:
    user: ENC[AES256_GCM,data:BNqSiF9P8kg=,iv:sR8De5gmSk79iCMdw8mreot4hq0Yz8jGgBEQ5Dl4lHI=,tag:KERHV6nvbOVHuM4cNFG/cw==,type:str]
kind: Secret
metadata:
    name: grafana-admin-user
sops:
    age:
        - recipient: age10k28kkfyvws4ukkk4qy5aw5talf24cyh9xluhxdmeysflgza3gsqvazsek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Vzlrd0lNdzVSZFQzQVI2
            bVhFL3I5NzhHanNMU1VkUUM3ZllxUHBLOFRVCmJ3bFUyWWIyQTVlWTVVZTJPUXc0
            NlJ1T1VrRHgybVlQZE5qTlVsTlRqV1EKLS0tIG03VXJWODZxeit2TW1oazR3N2E3
            elF3TWtrNnFwbzdCdERHeklIVUljNFUK0dn7Gufywdll4trszZ+OWMNoodMWvqwZ
            +DyW20Za8zaEQ9AiJZ/z53LIBgTAUssenhKwYLsmA5W0L7jC4u013A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T22:27:38Z"
    mac: ENC[AES256_GCM,data:Q38F5839vlIow2psNUwHyrMqMOF+RN8mvtPVrUm9yO8ZWhu31gfGLx34iVCFNYPSvVHXzHCg7m8pBhszfA2v2nlpWV1qqFhWChMZ+3iQCvT4u55PovyxfcQDFl1dSDdwU/ynVECZtb/1KRPnqWK50iMsWJjOlkgbJU05IRfH8ak=,iv:IwYgTVRAOxesSGB+t+O4+EcGgjoeJrJ2iwkvO5PuK24=,tag:oreAGNcasHZhbN09mzs2iw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
